spring:
  datasource:
    url: jdbc:mysql://localhost:3306/echo_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 5226809
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    root: INFO
    com.lanlan.echo: DEBUG